In [1]:
# -*- coding: utf-8 -*-
"""
   Introduction to Deep Learning (LDA-T3114)
   Skeleton Code for Assignment 1: Sentiment Classification on a Feed-Forward Neural Network

   Hande Celikkanat & Miikka Silfverberg
"""

'\n   Introduction to Deep Learning (LDA-T3114)\n   Skeleton Code for Assignment 1: Sentiment Classification on a Feed-Forward Neural Network\n\n   Hande Celikkanat & Miikka Silfverberg\n'

In [44]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import random

#ATTENTION: If necessary, add the paths to your data_semeval.py and paths.py here:
#import sys
#sys.path.append('</path/to/below/modules>')
from data_semeval import *
from paths import data_dir

In [79]:
#--- hyperparameters ---

N_CLASSES = len(LABEL_INDICES)
N_EPOCHS = 10
LEARNING_RATE = 0.05
BATCH_SIZE = 100
REPORT_EVERY = 1
IS_VERBOSE = True

In [80]:
def make_bow(tweet, indices):
    feature_ids = list(indices[tok] for tok in tweet['BODY'] if tok in indices)
    bow_vec = torch.zeros(len(indices))
    bow_vec[feature_ids] = 1
    return bow_vec.view(1, -1)

def generate_bow_representations(data):
    vocab = set(token for tweet in data['training'] for token in tweet['BODY'])
    vocab_size = len(vocab) 
    indices = {w:i for i, w in enumerate(vocab)}
  
    for split in ["training","development.input","development.gold",
                  "test.input","test.gold"]:
        for tweet in data[split]:
            tweet['BOW'] = make_bow(tweet,indices)

    return indices, vocab_size

# Convert string label to pytorch format.
def label_to_idx(label):
    return torch.LongTensor([LABEL_INDICES[label]])

In [118]:
#--- model ---

class FFNN(nn.Module):
    # Feel free to add whichever arguments you like here.
    def __init__(self, vocab_size, n_classes, extra_arg_1=None, extra_arg_2=None):
        super(FFNN, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(vocab_size, 512),
            nn.ReLU(),
            nn.Linear(512, n_classes)
        )
        pass

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [82]:
#--- data loading ---
data = read_semeval_datasets(data_dir)
indices, vocab_size = generate_bow_representations(data)

In [119]:
#--- set up ---

# WRITE CODE HERE
model = FFNN(vocab_size, N_CLASSES) #add extra arguments here if you use
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [120]:
import time

def time_ms():
    return round(time.time() * 1000)
    
#--- training ---
for epoch in range(N_EPOCHS):
    total_loss = 0
    # Generally speaking, it's a good idea to shuffle your
    # datasets once every epoch.
    random.shuffle(data['training'])  
    
    then = time_ms()

    for i in range(int(len(data['training'])/BATCH_SIZE)):
        minibatch = data['training'][i*BATCH_SIZE:(i+1)*BATCH_SIZE]
        
        X = torch.stack([x['BOW'] for x in minibatch])
        y = torch.as_tensor([label_to_idx(y['SENTIMENT']) for y in minibatch])
        
        # print(y)
        
        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    print(time_ms() - then)
    if ((epoch+1) % REPORT_EVERY) == 0:
        print('epoch: %d, loss: %.4f' % (epoch+1, total_loss*BATCH_SIZE/len(data['training'])))


6756
epoch: 1, loss: 0.0000
6182
epoch: 2, loss: 0.0000
6579
epoch: 3, loss: 0.0000
6725
epoch: 4, loss: 0.0000
6756
epoch: 5, loss: 0.0000
6740
epoch: 6, loss: 0.0000
6811
epoch: 7, loss: 0.0000
6531
epoch: 8, loss: 0.0000
6686
epoch: 9, loss: 0.0000
6564
epoch: 10, loss: 0.0000


In [121]:
#--- test ---
correct = 0
with torch.no_grad():
    for tweet in data['test.gold']:
        gold_class = label_to_idx(tweet['SENTIMENT'])

        bow = tweet['BOW']
        predicted = model(bow)
        
        print(predicted)
        print(gold_class)

        #if IS_VERBOSE:
        #    print('TEST DATA: %s, GOLD LABEL: %s, GOLD CLASS %d, OUTPUT: %d' % 
        #         (' '.join(tweet['BODY'][:-1]), tweet['SENTIMENT'], gold_class, predicted))

    print('test accuracy: %.2f' % (100.0 * correct / len(data['test.gold'])))

tensor([[-0.1702,  0.1449,  0.0398]])
tensor([1])
tensor([[-0.1726,  0.1566,  0.0425]])
tensor([1])
tensor([[-0.1852,  0.1708,  0.0489]])
tensor([0])
tensor([[-0.1736,  0.1519,  0.0413]])
tensor([2])
tensor([[-0.1599,  0.1529,  0.0419]])
tensor([1])
tensor([[-0.1830,  0.1579,  0.0635]])
tensor([2])
tensor([[-0.1735,  0.1438,  0.0435]])
tensor([2])
tensor([[-0.1681,  0.1362,  0.0314]])
tensor([2])
tensor([[-0.1760,  0.1567,  0.0296]])
tensor([2])
tensor([[-0.1685,  0.1489,  0.0429]])
tensor([0])
tensor([[-0.1823,  0.1332,  0.0440]])
tensor([2])
tensor([[-0.1594,  0.1375,  0.0383]])
tensor([1])
tensor([[-0.1706,  0.1556,  0.0273]])
tensor([0])
tensor([[-0.1717,  0.1430,  0.0327]])
tensor([1])
tensor([[-0.1551,  0.1451,  0.0423]])
tensor([1])
tensor([[-0.1614,  0.1426,  0.0385]])
tensor([1])
tensor([[-0.1785,  0.1652,  0.0445]])
tensor([1])
tensor([[-0.1837,  0.1610,  0.0524]])
tensor([1])
tensor([[-0.1867,  0.1455,  0.0518]])
tensor([1])
tensor([[-0.1734,  0.1449,  0.0367]])
tensor([2])


tensor([[-0.1783,  0.1659,  0.0281]])
tensor([1])
tensor([[-0.1421,  0.1139,  0.0444]])
tensor([2])
tensor([[-0.1706,  0.1494,  0.0465]])
tensor([2])
tensor([[-0.1979,  0.1763,  0.0418]])
tensor([2])
tensor([[-0.1812,  0.1583,  0.0449]])
tensor([0])
tensor([[-0.1987,  0.1665,  0.0417]])
tensor([1])
tensor([[-0.1738,  0.1383,  0.0358]])
tensor([0])
tensor([[-0.1760,  0.1498,  0.0405]])
tensor([1])
tensor([[-0.1845,  0.1592,  0.0460]])
tensor([1])
tensor([[-0.1576,  0.1406,  0.0480]])
tensor([2])
tensor([[-0.1745,  0.1516,  0.0389]])
tensor([0])
tensor([[-0.1670,  0.1407,  0.0510]])
tensor([2])
tensor([[-0.1470,  0.1319,  0.0334]])
tensor([1])
tensor([[-0.1522,  0.1356,  0.0392]])
tensor([1])
tensor([[-0.1885,  0.1496,  0.0501]])
tensor([1])
tensor([[-0.1700,  0.1436,  0.0376]])
tensor([1])
tensor([[-0.1886,  0.1581,  0.0330]])
tensor([2])
tensor([[-0.1648,  0.1498,  0.0396]])
tensor([2])
tensor([[-0.1682,  0.1464,  0.0444]])
tensor([1])
tensor([[-0.1701,  0.1484,  0.0420]])
tensor([0])


tensor([2])
tensor([[-0.1831,  0.1487,  0.0474]])
tensor([2])
tensor([[-0.1693,  0.1476,  0.0444]])
tensor([1])
tensor([[-0.1558,  0.1319,  0.0411]])
tensor([1])
tensor([[-0.1574,  0.1450,  0.0276]])
tensor([0])
tensor([[-0.1814,  0.1620,  0.0498]])
tensor([2])
tensor([[-0.1610,  0.1353,  0.0404]])
tensor([2])
tensor([[-0.1787,  0.1597,  0.0475]])
tensor([1])
tensor([[-0.1657,  0.1514,  0.0348]])
tensor([0])
tensor([[-0.1806,  0.1530,  0.0411]])
tensor([1])
tensor([[-0.1830,  0.1549,  0.0497]])
tensor([2])
tensor([[-0.1677,  0.1381,  0.0462]])
tensor([2])
tensor([[-0.1795,  0.1428,  0.0280]])
tensor([2])
tensor([[-0.1640,  0.1328,  0.0450]])
tensor([2])
tensor([[-0.1714,  0.1307,  0.0508]])
tensor([2])
tensor([[-0.1579,  0.1353,  0.0415]])
tensor([0])
tensor([[-0.1740,  0.1433,  0.0469]])
tensor([2])
tensor([[-0.1843,  0.1592,  0.0534]])
tensor([1])
tensor([[-0.1732,  0.1519,  0.0502]])
tensor([2])
tensor([[-0.1600,  0.1204,  0.0423]])
tensor([2])
tensor([[-0.1792,  0.1464,  0.0402]])


tensor([[-0.1703,  0.1336,  0.0456]])
tensor([2])
tensor([[-0.1854,  0.1566,  0.0444]])
tensor([2])
tensor([[-0.1741,  0.1482,  0.0488]])
tensor([2])
tensor([[-0.2019,  0.1562,  0.0498]])
tensor([2])
tensor([[-0.1876,  0.1681,  0.0413]])
tensor([2])
tensor([[-0.1730,  0.1429,  0.0429]])
tensor([1])
tensor([[-0.1583,  0.1411,  0.0438]])
tensor([1])
tensor([[-0.1830,  0.1427,  0.0520]])
tensor([2])
tensor([[-0.1719,  0.1470,  0.0476]])
tensor([2])
tensor([[-0.1621,  0.1340,  0.0396]])
tensor([2])
tensor([[-0.1758,  0.1518,  0.0447]])
tensor([1])
tensor([[-0.1860,  0.1610,  0.0476]])
tensor([1])
tensor([[-0.1879,  0.1525,  0.0415]])
tensor([2])
tensor([[-0.1820,  0.1506,  0.0481]])
tensor([2])
tensor([[-0.1547,  0.1260,  0.0320]])
tensor([1])
tensor([[-0.1563,  0.1351,  0.0308]])
tensor([1])
tensor([[-0.1733,  0.1478,  0.0475]])
tensor([1])
tensor([[-0.1805,  0.1658,  0.0464]])
tensor([2])
tensor([[-0.1726,  0.1481,  0.0360]])
tensor([1])
tensor([[-0.1757,  0.1452,  0.0470]])
tensor([1])


tensor([[-0.1778,  0.1554,  0.0411]])
tensor([2])
tensor([[-0.1594,  0.1281,  0.0446]])
tensor([0])
tensor([[-0.1895,  0.1584,  0.0459]])
tensor([2])
tensor([[-0.1989,  0.1559,  0.0627]])
tensor([2])
tensor([[-0.1750,  0.1609,  0.0416]])
tensor([1])
tensor([[-0.1679,  0.1567,  0.0367]])
tensor([1])
tensor([[-0.1822,  0.1565,  0.0420]])
tensor([2])
tensor([[-0.1928,  0.1690,  0.0553]])
tensor([2])
tensor([[-0.1574,  0.1317,  0.0391]])
tensor([2])
tensor([[-0.1600,  0.1339,  0.0428]])
tensor([1])
tensor([[-0.1722,  0.1409,  0.0429]])
tensor([2])
tensor([[-0.1692,  0.1457,  0.0376]])
tensor([0])
tensor([[-0.1731,  0.1492,  0.0320]])
tensor([1])
tensor([[-0.1517,  0.1234,  0.0286]])
tensor([0])
tensor([[-0.1632,  0.1362,  0.0351]])
tensor([1])
tensor([[-0.1640,  0.1377,  0.0454]])
tensor([0])
tensor([[-0.1680,  0.1396,  0.0280]])
tensor([1])
tensor([[-0.1588,  0.1478,  0.0411]])
tensor([2])
tensor([[-0.1760,  0.1581,  0.0422]])
tensor([2])
tensor([[-0.1583,  0.1411,  0.0438]])
tensor([1])


tensor([[-0.1908,  0.1648,  0.0528]])
tensor([2])
tensor([[-0.1524,  0.1267,  0.0371]])
tensor([1])
tensor([[-0.1671,  0.1302,  0.0476]])
tensor([1])
tensor([[-0.1559,  0.1269,  0.0445]])
tensor([0])
tensor([[-0.1583,  0.1321,  0.0324]])
tensor([1])
tensor([[-0.1656,  0.1445,  0.0327]])
tensor([2])
tensor([[-0.1772,  0.1536,  0.0314]])
tensor([0])
tensor([[-0.1660,  0.1416,  0.0425]])
tensor([1])
tensor([[-0.1635,  0.1429,  0.0350]])
tensor([1])
tensor([[-0.1667,  0.1364,  0.0393]])
tensor([1])
tensor([[-0.1630,  0.1488,  0.0334]])
tensor([1])
tensor([[-0.1653,  0.1405,  0.0417]])
tensor([1])
tensor([[-0.1750,  0.1348,  0.0457]])
tensor([2])
tensor([[-0.1782,  0.1362,  0.0502]])
tensor([2])
tensor([[-0.1739,  0.1643,  0.0451]])
tensor([1])
tensor([[-0.1746,  0.1336,  0.0477]])
tensor([2])
tensor([[-0.1527,  0.1311,  0.0434]])
tensor([0])
tensor([[-0.1788,  0.1546,  0.0501]])
tensor([1])
tensor([[-0.1402,  0.1142,  0.0352]])
tensor([2])
tensor([[-0.1532,  0.1346,  0.0403]])
tensor([2])


tensor([[-0.1605,  0.1523,  0.0419]])
tensor([2])
tensor([[-0.1631,  0.1503,  0.0364]])
tensor([0])
tensor([[-0.1790,  0.1621,  0.0435]])
tensor([1])
tensor([[-0.1659,  0.1373,  0.0483]])
tensor([2])
tensor([[-0.1769,  0.1349,  0.0471]])
tensor([2])
tensor([[-0.1763,  0.1430,  0.0420]])
tensor([2])
tensor([[-0.1511,  0.1260,  0.0264]])
tensor([1])
tensor([[-0.1672,  0.1316,  0.0501]])
tensor([1])
tensor([[-0.1888,  0.1744,  0.0498]])
tensor([1])
tensor([[-0.1601,  0.1354,  0.0447]])
tensor([2])
tensor([[-0.1692,  0.1567,  0.0386]])
tensor([1])
tensor([[-0.1689,  0.1523,  0.0396]])
tensor([1])
tensor([[-0.1914,  0.1570,  0.0460]])
tensor([1])
tensor([[-0.1923,  0.1509,  0.0532]])
tensor([1])
tensor([[-0.1710,  0.1509,  0.0417]])
tensor([1])
tensor([[-0.1639,  0.1452,  0.0352]])
tensor([1])
tensor([[-0.1828,  0.1535,  0.0468]])
tensor([1])
tensor([[-0.1577,  0.1354,  0.0251]])
tensor([1])
tensor([[-0.1831,  0.1626,  0.0458]])
tensor([1])
tensor([[-0.1734,  0.1532,  0.0557]])
tensor([2])


tensor([[-0.1810,  0.1431,  0.0489]])
tensor([2])
tensor([[-0.1626,  0.1395,  0.0358]])
tensor([1])
tensor([[-0.1975,  0.1742,  0.0429]])
tensor([1])
tensor([[-0.1787,  0.1586,  0.0475]])
tensor([1])
tensor([[-0.1716,  0.1424,  0.0372]])
tensor([1])
tensor([[-0.1791,  0.1480,  0.0359]])
tensor([2])
tensor([[-0.1823,  0.1550,  0.0352]])
tensor([2])
tensor([[-0.1748,  0.1407,  0.0426]])
tensor([2])
tensor([[-0.1991,  0.1571,  0.0505]])
tensor([1])
tensor([[-0.1759,  0.1430,  0.0377]])
tensor([2])
tensor([[-0.1911,  0.1553,  0.0482]])
tensor([1])
tensor([[-0.1622,  0.1380,  0.0430]])
tensor([1])
tensor([[-0.1750,  0.1489,  0.0483]])
tensor([2])
tensor([[-0.1737,  0.1558,  0.0488]])
tensor([2])
tensor([[-0.1730,  0.1484,  0.0389]])
tensor([0])
tensor([[-0.1717,  0.1476,  0.0422]])
tensor([2])
tensor([[-0.1653,  0.1446,  0.0531]])
tensor([2])
tensor([[-0.1668,  0.1338,  0.0394]])
tensor([2])
tensor([[-0.1676,  0.1325,  0.0429]])
tensor([2])
tensor([[-0.1671,  0.1411,  0.0492]])
tensor([1])


tensor([[-0.1608,  0.1487,  0.0411]])
tensor([1])
tensor([[-0.1664,  0.1420,  0.0460]])
tensor([2])
tensor([[-0.1815,  0.1577,  0.0332]])
tensor([1])
tensor([[-0.1844,  0.1497,  0.0456]])
tensor([1])
tensor([[-0.1842,  0.1569,  0.0483]])
tensor([2])
tensor([[-0.1717,  0.1483,  0.0541]])
tensor([2])
tensor([[-0.1700,  0.1413,  0.0477]])
tensor([2])
tensor([[-0.1749,  0.1633,  0.0476]])
tensor([0])
tensor([[-0.1750,  0.1463,  0.0439]])
tensor([1])
tensor([[-0.1791,  0.1544,  0.0340]])
tensor([2])
tensor([[-0.1906,  0.1709,  0.0586]])
tensor([2])
tensor([[-0.1707,  0.1499,  0.0324]])
tensor([0])
tensor([[-0.1570,  0.1409,  0.0516]])
tensor([1])
tensor([[-0.1612,  0.1427,  0.0262]])
tensor([1])
tensor([[-0.1460,  0.1175,  0.0337]])
tensor([2])
tensor([[-0.1632,  0.1386,  0.0302]])
tensor([1])
tensor([[-0.1595,  0.1384,  0.0297]])
tensor([1])
tensor([[-0.1795,  0.1496,  0.0464]])
tensor([2])
tensor([[-0.1791,  0.1551,  0.0470]])
tensor([1])
tensor([[-0.1615,  0.1377,  0.0446]])
tensor([2])


tensor([1])
tensor([[-0.1696,  0.1426,  0.0380]])
tensor([1])
tensor([[-0.1457,  0.1270,  0.0374]])
tensor([1])
tensor([[-0.1771,  0.1497,  0.0441]])
tensor([1])
tensor([[-0.1687,  0.1511,  0.0476]])
tensor([2])
tensor([[-0.1679,  0.1415,  0.0393]])
tensor([2])
tensor([[-0.1747,  0.1405,  0.0441]])
tensor([2])
tensor([[-0.1796,  0.1633,  0.0380]])
tensor([1])
tensor([[-0.1592,  0.1357,  0.0397]])
tensor([2])
tensor([[-0.1835,  0.1448,  0.0361]])
tensor([2])
tensor([[-0.1547,  0.1498,  0.0338]])
tensor([0])
tensor([[-0.1861,  0.1649,  0.0506]])
tensor([2])
tensor([[-0.1689,  0.1536,  0.0372]])
tensor([2])
tensor([[-0.1592,  0.1283,  0.0411]])
tensor([1])
tensor([[-0.1513,  0.1277,  0.0378]])
tensor([2])
tensor([[-0.1680,  0.1459,  0.0225]])
tensor([1])
tensor([[-0.1692,  0.1372,  0.0351]])
tensor([1])
tensor([[-0.1699,  0.1458,  0.0309]])
tensor([2])
tensor([[-0.1670,  0.1368,  0.0424]])
tensor([2])
tensor([[-0.1814,  0.1636,  0.0497]])
tensor([0])
tensor([[-0.1882,  0.1684,  0.0436]])


tensor([[-0.1674,  0.1444,  0.0403]])
tensor([1])
tensor([[-0.1505,  0.1309,  0.0428]])
tensor([2])
tensor([[-0.1676,  0.1484,  0.0400]])
tensor([1])
tensor([[-0.1609,  0.1359,  0.0430]])
tensor([2])
tensor([[-0.1722,  0.1418,  0.0551]])
tensor([0])
tensor([[-0.1879,  0.1678,  0.0357]])
tensor([1])
tensor([[-0.1864,  0.1692,  0.0436]])
tensor([1])
tensor([[-0.1833,  0.1464,  0.0446]])
tensor([2])
tensor([[-0.1754,  0.1410,  0.0430]])
tensor([2])
tensor([[-0.1432,  0.1197,  0.0333]])
tensor([1])
tensor([[-0.1719,  0.1388,  0.0517]])
tensor([1])
tensor([[-0.1650,  0.1405,  0.0480]])
tensor([1])
tensor([[-0.1947,  0.1778,  0.0429]])
tensor([2])
tensor([[-0.1752,  0.1513,  0.0366]])
tensor([1])
tensor([[-0.1627,  0.1484,  0.0396]])
tensor([1])
tensor([[-0.1521,  0.1210,  0.0507]])
tensor([2])
tensor([[-0.1800,  0.1491,  0.0538]])
tensor([2])
tensor([[-0.1881,  0.1637,  0.0470]])
tensor([2])
tensor([[-0.1880,  0.1677,  0.0441]])
tensor([0])
tensor([[-0.1730,  0.1493,  0.0352]])
tensor([1])


tensor([[-0.1579,  0.1286,  0.0460]])
tensor([1])
tensor([[-0.1675,  0.1527,  0.0371]])
tensor([1])
tensor([[-0.1921,  0.1720,  0.0516]])
tensor([2])
tensor([[-0.1841,  0.1620,  0.0375]])
tensor([1])
tensor([[-0.1616,  0.1296,  0.0381]])
tensor([2])
tensor([[-0.1944,  0.1589,  0.0313]])
tensor([2])
tensor([[-0.1844,  0.1635,  0.0515]])
tensor([2])
tensor([[-0.1686,  0.1414,  0.0509]])
tensor([1])
tensor([[-0.1681,  0.1449,  0.0378]])
tensor([1])
tensor([[-0.2006,  0.1612,  0.0538]])
tensor([2])
tensor([[-0.1807,  0.1380,  0.0475]])
tensor([2])
tensor([[-0.1800,  0.1529,  0.0337]])
tensor([0])
tensor([[-0.1646,  0.1410,  0.0360]])
tensor([1])
tensor([[-0.1858,  0.1594,  0.0447]])
tensor([1])
tensor([[-0.1776,  0.1468,  0.0425]])
tensor([2])
tensor([[-0.1584,  0.1241,  0.0195]])
tensor([1])
tensor([[-0.1687,  0.1518,  0.0332]])
tensor([1])
tensor([[-0.1746,  0.1681,  0.0381]])
tensor([2])
tensor([[-0.1782,  0.1461,  0.0375]])
tensor([1])
tensor([[-0.1712,  0.1445,  0.0460]])
tensor([2])


tensor([[-0.1686,  0.1602,  0.0411]])
tensor([2])
tensor([[-0.1809,  0.1515,  0.0534]])
tensor([1])
tensor([[-0.1687,  0.1512,  0.0492]])
tensor([1])
tensor([[-0.1859,  0.1542,  0.0583]])
tensor([0])
tensor([[-0.1836,  0.1486,  0.0488]])
tensor([2])
tensor([[-0.1690,  0.1439,  0.0386]])
tensor([1])
tensor([[-0.1828,  0.1515,  0.0304]])
tensor([1])
tensor([[-0.1616,  0.1350,  0.0414]])
tensor([2])
tensor([[-0.1655,  0.1593,  0.0397]])
tensor([2])
tensor([[-0.1702,  0.1545,  0.0542]])
tensor([0])
tensor([[-0.1780,  0.1516,  0.0526]])
tensor([2])
tensor([[-0.1533,  0.1259,  0.0380]])
tensor([1])
tensor([[-0.1671,  0.1518,  0.0403]])
tensor([2])
tensor([[-0.1771,  0.1466,  0.0412]])
tensor([2])
tensor([[-0.1642,  0.1438,  0.0355]])
tensor([1])
tensor([[-0.1491,  0.1287,  0.0374]])
tensor([1])
tensor([[-0.1926,  0.1550,  0.0517]])
tensor([2])
tensor([[-0.1855,  0.1746,  0.0394]])
tensor([1])
tensor([[-0.1727,  0.1582,  0.0415]])
tensor([2])
tensor([[-0.1693,  0.1570,  0.0338]])
tensor([0])


tensor([[-0.1540,  0.1235,  0.0397]])
tensor([2])
tensor([[-0.1696,  0.1305,  0.0356]])
tensor([1])
tensor([[-0.1773,  0.1438,  0.0377]])
tensor([1])
tensor([[-0.1619,  0.1420,  0.0426]])
tensor([2])
tensor([[-0.1662,  0.1346,  0.0343]])
tensor([0])
tensor([[-0.1685,  0.1405,  0.0492]])
tensor([2])
tensor([[-0.1643,  0.1353,  0.0429]])
tensor([0])
tensor([[-0.1819,  0.1632,  0.0424]])
tensor([1])
tensor([[-0.1767,  0.1498,  0.0471]])
tensor([1])
tensor([[-0.1962,  0.1607,  0.0578]])
tensor([0])
tensor([[-0.1762,  0.1456,  0.0438]])
tensor([1])
tensor([[-0.1630,  0.1499,  0.0497]])
tensor([2])
tensor([[-0.1562,  0.1374,  0.0427]])
tensor([2])
tensor([[-0.1795,  0.1476,  0.0436]])
tensor([1])
tensor([[-0.1655,  0.1425,  0.0291]])
tensor([2])
tensor([[-0.1775,  0.1533,  0.0220]])
tensor([2])
tensor([[-0.1610,  0.1311,  0.0314]])
tensor([2])
tensor([[-0.1738,  0.1489,  0.0348]])
tensor([1])
tensor([[-0.1604,  0.1345,  0.0482]])
tensor([2])
tensor([[-0.1650,  0.1381,  0.0351]])
tensor([1])


tensor([[-0.1586,  0.1405,  0.0319]])
tensor([1])
tensor([[-0.1919,  0.1416,  0.0535]])
tensor([2])
tensor([[-0.1723,  0.1397,  0.0322]])
tensor([1])
tensor([[-0.1795,  0.1534,  0.0541]])
tensor([2])
tensor([[-0.1780,  0.1502,  0.0536]])
tensor([2])
tensor([[-0.1449,  0.1313,  0.0363]])
tensor([0])
tensor([[-0.1864,  0.1500,  0.0550]])
tensor([1])
tensor([[-0.1614,  0.1492,  0.0332]])
tensor([1])
tensor([[-0.1974,  0.1711,  0.0483]])
tensor([2])
tensor([[-0.1702,  0.1498,  0.0387]])
tensor([1])
tensor([[-0.1884,  0.1435,  0.0463]])
tensor([2])
tensor([[-0.1619,  0.1383,  0.0422]])
tensor([2])
tensor([[-0.1480,  0.1242,  0.0324]])
tensor([1])
tensor([[-0.1733,  0.1588,  0.0409]])
tensor([1])
tensor([[-0.1579,  0.1350,  0.0490]])
tensor([0])
tensor([[-0.1650,  0.1397,  0.0341]])
tensor([1])
tensor([[-0.1827,  0.1707,  0.0378]])
tensor([2])
tensor([[-0.1787,  0.1596,  0.0201]])
tensor([1])
tensor([[-0.1678,  0.1424,  0.0556]])
tensor([2])
tensor([[-0.1830,  0.1515,  0.0429]])
tensor([2])


tensor([[-0.1818,  0.1526,  0.0451]])
tensor([2])
tensor([[-0.1716,  0.1570,  0.0580]])
tensor([2])
tensor([[-0.1804,  0.1643,  0.0513]])
tensor([2])
tensor([[-0.1782,  0.1540,  0.0476]])
tensor([2])
tensor([[-0.1794,  0.1495,  0.0489]])
tensor([2])
tensor([[-0.1566,  0.1278,  0.0349]])
tensor([2])
tensor([[-0.1723,  0.1478,  0.0325]])
tensor([1])
tensor([[-0.1628,  0.1198,  0.0390]])
tensor([2])
tensor([[-0.1902,  0.1530,  0.0502]])
tensor([1])
tensor([[-0.1524,  0.1298,  0.0393]])
tensor([2])
tensor([[-0.1777,  0.1484,  0.0454]])
tensor([2])
tensor([[-0.1613,  0.1407,  0.0375]])
tensor([1])
tensor([[-0.1787,  0.1533,  0.0374]])
tensor([2])
tensor([[-0.2066,  0.1767,  0.0433]])
tensor([1])
tensor([[-0.1732,  0.1505,  0.0354]])
tensor([2])
tensor([[-0.1770,  0.1575,  0.0420]])
tensor([2])
tensor([[-0.1788,  0.1475,  0.0550]])
tensor([2])
tensor([[-0.1777,  0.1647,  0.0416]])
tensor([2])
tensor([[-0.1912,  0.1643,  0.0355]])
tensor([1])
tensor([[-0.1911,  0.1467,  0.0351]])
tensor([2])


tensor([[-0.1558,  0.1351,  0.0398]])
tensor([2])
tensor([[-0.1634,  0.1336,  0.0334]])
tensor([1])
tensor([[-0.1650,  0.1385,  0.0390]])
tensor([2])
tensor([[-0.1574,  0.1340,  0.0432]])
tensor([2])
tensor([[-0.1800,  0.1621,  0.0314]])
tensor([1])
tensor([[-0.1878,  0.1663,  0.0615]])
tensor([2])
tensor([[-0.1782,  0.1475,  0.0492]])
tensor([2])
tensor([[-0.1715,  0.1403,  0.0383]])
tensor([1])
tensor([[-0.1670,  0.1510,  0.0450]])
tensor([1])
tensor([[-0.1889,  0.1661,  0.0372]])
tensor([1])
tensor([[-0.1713,  0.1417,  0.0444]])
tensor([1])
tensor([[-0.1662,  0.1376,  0.0342]])
tensor([2])
tensor([[-0.1863,  0.1646,  0.0398]])
tensor([2])
tensor([[-0.1667,  0.1407,  0.0394]])
tensor([1])
tensor([[-0.1865,  0.1656,  0.0458]])
tensor([2])
tensor([[-0.1869,  0.1695,  0.0346]])
tensor([0])
tensor([[-0.1564,  0.1391,  0.0379]])
tensor([1])
tensor([[-0.1617,  0.1361,  0.0485]])
tensor([1])
tensor([[-0.1521,  0.1328,  0.0373]])
tensor([1])
tensor([[-0.1790,  0.1546,  0.0415]])
tensor([0])


tensor([[-0.1587,  0.1273,  0.0444]])
tensor([1])
tensor([[-0.1867,  0.1603,  0.0381]])
tensor([2])
tensor([[-0.1663,  0.1376,  0.0560]])
tensor([2])
tensor([[-0.1572,  0.1273,  0.0358]])
tensor([1])
tensor([[-0.1695,  0.1521,  0.0429]])
tensor([1])
tensor([[-0.1854,  0.1550,  0.0506]])
tensor([1])
tensor([[-0.1855,  0.1443,  0.0577]])
tensor([2])
tensor([[-0.1733,  0.1451,  0.0439]])
tensor([2])
tensor([[-0.1695,  0.1339,  0.0338]])
tensor([2])
tensor([[-0.1611,  0.1267,  0.0426]])
tensor([1])
tensor([[-0.1708,  0.1473,  0.0375]])
tensor([2])
tensor([[-0.1563,  0.1227,  0.0354]])
tensor([2])
tensor([[-0.1736,  0.1671,  0.0414]])
tensor([0])
tensor([[-0.2018,  0.1697,  0.0488]])
tensor([2])
tensor([[-0.1754,  0.1567,  0.0440]])
tensor([0])
tensor([[-0.1658,  0.1415,  0.0233]])
tensor([1])
tensor([[-0.1778,  0.1504,  0.0406]])
tensor([2])
tensor([[-0.1732,  0.1503,  0.0469]])
tensor([2])
tensor([[-0.1742,  0.1413,  0.0452]])
tensor([2])
tensor([[-0.1558,  0.1278,  0.0336]])
tensor([1])


tensor([[-0.1877,  0.1676,  0.0420]])
tensor([0])
tensor([[-0.1774,  0.1500,  0.0506]])
tensor([2])
tensor([[-0.1778,  0.1513,  0.0467]])
tensor([1])
tensor([[-0.1588,  0.1360,  0.0425]])
tensor([2])
tensor([[-0.1826,  0.1533,  0.0425]])
tensor([0])
tensor([[-0.1587,  0.1362,  0.0369]])
tensor([2])
tensor([[-0.1743,  0.1446,  0.0434]])
tensor([2])
tensor([[-0.1804,  0.1618,  0.0402]])
tensor([1])
tensor([[-0.1921,  0.1574,  0.0413]])
tensor([2])
tensor([[-0.1747,  0.1487,  0.0541]])
tensor([1])
tensor([[-0.1509,  0.1227,  0.0320]])
tensor([1])
tensor([[-0.1839,  0.1593,  0.0433]])
tensor([2])
tensor([[-0.1664,  0.1295,  0.0336]])
tensor([2])
tensor([[-0.1815,  0.1500,  0.0464]])
tensor([1])
tensor([[-0.1739,  0.1431,  0.0405]])
tensor([1])
tensor([[-0.1561,  0.1329,  0.0342]])
tensor([1])
tensor([[-0.1893,  0.1533,  0.0331]])
tensor([1])
tensor([[-0.1642,  0.1471,  0.0412]])
tensor([2])
tensor([[-0.1724,  0.1472,  0.0478]])
tensor([2])
tensor([[-0.1643,  0.1421,  0.0418]])
tensor([0])


tensor([[-0.1822,  0.1511,  0.0490]])
tensor([0])
tensor([[-0.1450,  0.1324,  0.0341]])
tensor([0])
tensor([[-0.1889,  0.1752,  0.0497]])
tensor([1])
tensor([[-0.1723,  0.1552,  0.0302]])
tensor([1])
tensor([[-0.1898,  0.1562,  0.0410]])
tensor([0])
tensor([[-0.1775,  0.1559,  0.0344]])
tensor([1])
tensor([[-0.1612,  0.1406,  0.0416]])
tensor([1])
tensor([[-0.1687,  0.1429,  0.0355]])
tensor([1])
tensor([[-0.1876,  0.1636,  0.0407]])
tensor([2])
tensor([[-0.1770,  0.1478,  0.0516]])
tensor([2])
tensor([[-0.1700,  0.1471,  0.0413]])
tensor([1])
tensor([[-0.1727,  0.1360,  0.0323]])
tensor([0])
tensor([[-0.1975,  0.1767,  0.0628]])
tensor([1])
tensor([[-0.1678,  0.1378,  0.0372]])
tensor([1])
tensor([[-0.1740,  0.1411,  0.0460]])
tensor([2])
tensor([[-0.1771,  0.1586,  0.0441]])
tensor([1])
tensor([[-0.1664,  0.1259,  0.0498]])
tensor([2])
tensor([[-0.1695,  0.1517,  0.0412]])
tensor([0])
tensor([[-0.1588,  0.1364,  0.0394]])
tensor([2])
tensor([[-0.1372,  0.1065,  0.0517]])
tensor([2])


tensor([[-0.1700,  0.1380,  0.0497]])
tensor([2])
tensor([[-0.1740,  0.1516,  0.0305]])
tensor([1])
tensor([[-0.1833,  0.1390,  0.0379]])
tensor([2])
tensor([[-0.1629,  0.1357,  0.0441]])
tensor([0])
tensor([[-0.1672,  0.1368,  0.0505]])
tensor([0])
tensor([[-0.1641,  0.1524,  0.0382]])
tensor([1])
tensor([[-0.1739,  0.1504,  0.0351]])
tensor([1])
tensor([[-0.1654,  0.1302,  0.0471]])
tensor([2])
tensor([[-0.1658,  0.1340,  0.0387]])
tensor([2])
tensor([[-0.1846,  0.1627,  0.0446]])
tensor([2])
tensor([[-0.1711,  0.1419,  0.0455]])
tensor([2])
tensor([[-0.1885,  0.1658,  0.0478]])
tensor([2])
tensor([[-0.1789,  0.1495,  0.0406]])
tensor([2])
tensor([[-0.1495,  0.1145,  0.0418]])
tensor([0])
tensor([[-0.1517,  0.1167,  0.0332]])
tensor([1])
tensor([[-0.1625,  0.1376,  0.0321]])
tensor([0])
tensor([[-0.1638,  0.1435,  0.0430]])
tensor([1])
tensor([[-0.1818,  0.1535,  0.0415]])
tensor([2])
tensor([[-0.1620,  0.1362,  0.0477]])
tensor([2])
tensor([[-0.1747,  0.1523,  0.0357]])
tensor([2])


tensor([[-0.1865,  0.1584,  0.0351]])
tensor([1])
tensor([[-0.1816,  0.1547,  0.0409]])
tensor([2])
tensor([[-0.1903,  0.1470,  0.0488]])
tensor([1])
tensor([[-0.1668,  0.1496,  0.0283]])
tensor([1])
tensor([[-0.1467,  0.1254,  0.0403]])
tensor([1])
tensor([[-0.1639,  0.1466,  0.0309]])
tensor([2])
tensor([[-0.1725,  0.1571,  0.0594]])
tensor([0])
tensor([[-0.1800,  0.1517,  0.0368]])
tensor([1])
tensor([[-0.1697,  0.1505,  0.0389]])
tensor([2])
tensor([[-0.1807,  0.1578,  0.0542]])
tensor([2])
tensor([[-0.1638,  0.1358,  0.0569]])
tensor([2])
tensor([[-0.1881,  0.1775,  0.0423]])
tensor([2])
tensor([[-0.1458,  0.1308,  0.0317]])
tensor([2])
tensor([[-0.1931,  0.1661,  0.0452]])
tensor([0])
tensor([[-0.1624,  0.1388,  0.0316]])
tensor([2])
tensor([[-0.1464,  0.1256,  0.0357]])
tensor([1])
tensor([[-0.1724,  0.1412,  0.0411]])
tensor([2])
tensor([[-0.1761,  0.1417,  0.0464]])
tensor([0])
tensor([[-0.1804,  0.1415,  0.0526]])
tensor([0])
tensor([[-0.1806,  0.1553,  0.0406]])
tensor([2])


tensor([[-0.1656,  0.1445,  0.0328]])
tensor([2])
tensor([[-0.1737,  0.1402,  0.0436]])
tensor([2])
tensor([[-0.1626,  0.1332,  0.0338]])
tensor([2])
tensor([[-0.1776,  0.1540,  0.0400]])
tensor([2])
tensor([[-0.1725,  0.1444,  0.0424]])
tensor([2])
tensor([[-0.1675,  0.1492,  0.0421]])
tensor([1])
tensor([[-0.1578,  0.1345,  0.0452]])
tensor([2])
tensor([[-0.1777,  0.1370,  0.0360]])
tensor([1])
tensor([[-0.1867,  0.1497,  0.0481]])
tensor([2])
tensor([[-0.1489,  0.1211,  0.0399]])
tensor([0])
tensor([[-0.1731,  0.1417,  0.0498]])
tensor([1])
tensor([[-0.1817,  0.1520,  0.0300]])
tensor([2])
tensor([[-0.1665,  0.1474,  0.0418]])
tensor([1])
tensor([[-0.1519,  0.1311,  0.0423]])
tensor([2])
tensor([[-0.1622,  0.1277,  0.0304]])
tensor([1])
tensor([[-0.1700,  0.1525,  0.0334]])
tensor([1])
tensor([[-0.1918,  0.1525,  0.0535]])
tensor([1])
tensor([[-0.1541,  0.1344,  0.0422]])
tensor([0])
tensor([[-0.1711,  0.1481,  0.0372]])
tensor([2])
tensor([[-0.1760,  0.1411,  0.0420]])
tensor([2])


tensor([[-0.1789,  0.1599,  0.0405]])
tensor([2])
tensor([[-0.1849,  0.1553,  0.0436]])
tensor([2])
tensor([[-0.1590,  0.1391,  0.0366]])
tensor([2])
tensor([[-0.1811,  0.1603,  0.0400]])
tensor([1])
tensor([[-0.1674,  0.1391,  0.0330]])
tensor([2])
tensor([[-0.1802,  0.1582,  0.0370]])
tensor([1])
tensor([[-0.1555,  0.1338,  0.0440]])
tensor([2])
tensor([[-0.1689,  0.1580,  0.0404]])
tensor([1])
tensor([[-0.1792,  0.1556,  0.0447]])
tensor([2])
tensor([[-0.1670,  0.1534,  0.0274]])
tensor([1])
tensor([[-0.1694,  0.1294,  0.0404]])
tensor([2])
tensor([[-0.1624,  0.1330,  0.0328]])
tensor([2])
tensor([[-0.1752,  0.1549,  0.0405]])
tensor([0])
tensor([[-0.1723,  0.1513,  0.0473]])
tensor([0])
tensor([[-0.1926,  0.1639,  0.0439]])
tensor([2])
tensor([[-0.1880,  0.1587,  0.0365]])
tensor([0])
tensor([[-0.1650,  0.1352,  0.0434]])
tensor([1])
tensor([[-0.1834,  0.1648,  0.0384]])
tensor([2])
tensor([[-0.1646,  0.1305,  0.0547]])
tensor([1])
tensor([[-0.1871,  0.1666,  0.0514]])
tensor([1])


tensor([[-0.1603,  0.1390,  0.0499]])
tensor([2])
tensor([[-0.1575,  0.1416,  0.0373]])
tensor([0])
tensor([[-0.1742,  0.1471,  0.0383]])
tensor([2])
tensor([[-0.1642,  0.1383,  0.0448]])
tensor([1])
tensor([[-0.1674,  0.1375,  0.0509]])
tensor([1])
tensor([[-0.1610,  0.1299,  0.0345]])
tensor([0])
tensor([[-0.1746,  0.1389,  0.0372]])
tensor([1])
tensor([[-0.1498,  0.1246,  0.0447]])
tensor([0])
tensor([[-0.1814,  0.1536,  0.0329]])
tensor([1])
tensor([[-0.1990,  0.1759,  0.0448]])
tensor([2])
tensor([[-0.1843,  0.1490,  0.0493]])
tensor([2])
tensor([[-0.1606,  0.1366,  0.0301]])
tensor([2])
tensor([[-0.1780,  0.1469,  0.0437]])
tensor([2])
tensor([[-0.1686,  0.1577,  0.0490]])
tensor([2])
tensor([[-0.1597,  0.1284,  0.0440]])
tensor([2])
tensor([[-0.1812,  0.1688,  0.0403]])
tensor([2])
tensor([[-0.1545,  0.1277,  0.0383]])
tensor([2])
tensor([[-0.1553,  0.1357,  0.0471]])
tensor([1])
tensor([[-0.1605,  0.1325,  0.0457]])
tensor([1])
tensor([[-0.1670,  0.1436,  0.0282]])
tensor([0])


tensor([[-0.1932,  0.1599,  0.0603]])
tensor([2])
tensor([[-0.1764,  0.1444,  0.0449]])
tensor([2])
tensor([[-0.1521,  0.1353,  0.0327]])
tensor([2])
tensor([[-0.1514,  0.1260,  0.0426]])
tensor([0])
tensor([[-0.1905,  0.1438,  0.0497]])
tensor([1])
tensor([[-0.1563,  0.1439,  0.0488]])
tensor([1])
tensor([[-0.1571,  0.1361,  0.0249]])
tensor([2])
tensor([[-0.1685,  0.1523,  0.0292]])
tensor([1])
tensor([[-0.1586,  0.1155,  0.0409]])
tensor([2])
tensor([[-0.1640,  0.1366,  0.0356]])
tensor([1])
tensor([[-0.1727,  0.1517,  0.0414]])
tensor([2])
tensor([[-0.1687,  0.1348,  0.0480]])
tensor([0])
tensor([[-0.1823,  0.1573,  0.0383]])
tensor([0])
tensor([[-0.1671,  0.1486,  0.0360]])
tensor([1])
tensor([[-0.1614,  0.1396,  0.0379]])
tensor([2])
tensor([[-0.1651,  0.1351,  0.0425]])
tensor([2])
tensor([[-0.1792,  0.1609,  0.0364]])
tensor([1])
tensor([[-0.1431,  0.1151,  0.0270]])
tensor([2])
tensor([[-0.1531,  0.1281,  0.0462]])
tensor([2])
tensor([[-0.1774,  0.1457,  0.0516]])
tensor([2])
